@baseUrl=http://192.168.0.51:3000
@adminToken=26df74f26be27de534dfc7232b42b395706f49e26ff4891d816f38b0b1556fa2


###############################################  




############################################### 




############################################### 




###############################################  




############################################### 




############################################### 

















































































































###############################################  Admin TOKEN TOKEN TOKEN OK OK OK

POST {{baseUrl}}/admin-api
Content-Type: application/json

{
  "query": "mutation Login { authenticate(input: { native: { username: \"superadmin\", password: \"superadmin\" } }) { ... on CurrentUser { id identifier } } }"
}

###############################################  Admin TOKEN TOKEN TOKEN OK OK OK