### Vendure Admin API Role Cloning Environment Setup
@baseUrl = http://192.168.0.51:3000/admin-api
@authToken = def6e6c5f8b9c3b89d6d273542617fe416716e1147557d2c33d1d2e826f16c6f

###### defaultLanguageCode defaultCurrencyCode createdAt 

POST h ttp://192.168.0.51:3000/admin-api
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "query": "query GetAllChannels { channels { items { id code token } } }"
}

#################################################################
### STEP 1: Fetch the Source Role Details
#################################################################
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "query": "query GetRoleToClone($id: ID!) { role(id: $id) { id code description permissions channels { id } } }",
  "variables": {
    "id": "3" 
  }
}

###

#################################################################
### STEP 2: Create the Cloned Role
### Use the output arrays from Step 1 to fill variables below
#################################################################
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "query": "mutation CloneRole($input: CreateRoleInput!) { createRole(input: $input) { id code description permissions } }",
  "variables": {
    "input": {
      "code": "Admin_Wang",
      "description": "Admin_Wang, Clone from Administrator",
       "permissions": [
        "Authenticated",
        "CreateCatalog",
        "ReadCatalog",
        "UpdateCatalog",
        "DeleteCatalog",
        "CreateCustomer",
        "ReadCustomer",
        "UpdateCustomer",
        "DeleteCustomer",
        "CreateCustomerGroup",
        "ReadCustomerGroup",
        "UpdateCustomerGroup",
        "DeleteCustomerGroup",
        "CreateOrder",
        "ReadOrder",
        "UpdateOrder",
        "DeleteOrder"
      ],
      "channelIds": [
        "3"
      ]
    }
  }
}








###############################################  Admin TOKEN TOKEN TOKEN OK OK OK

#### Admin API --> TOKEN TOKEN TOKEN ---- OK OK OK
POST h ttp://192.168.0.51:3000/admin-api
Content-Type: application/json

{
  "query": "mutation Login { authenticate(input: { native: { username: \"superadmin\", password: \"superadmin\" } }) { ... on CurrentUser { id identifier } } }"
}


###
@admin_token=be42121b2ecd6a16496ddafaef13c77762f132db1ba66c412a730568a00c9e6e

###############################################  TOKEN TOKEN TOKEN OK OK OK OK OK









###############################################  Shop TOKEN TOKEN TOKEN OK OK OK

POST h ttp://192.168.0.51:3000/shop-api
Content-Type: application/json

{
  "query": "mutation Login { authenticate(input: { native: { username: \"tprice@163.com\", password: \"tttttttt\" } }) { ... on CurrentUser { id identifier } } }"
}

###############################################  Shop TOKEN TOKEN TOKEN OK OK OK