###############################################  Shop TOKEN TOKEN TOKEN OK OK OK

POST http://192.168.0.53:3000/shop-api
Content-Type: application/json

{
  "query": "mutation Login { authenticate(input: { native: { username: \"tprice@163.com\", password: \"tttttttt\" } }) { ... on CurrentUser { id identifier } } }"
}

###############################################  Shop TOKEN TOKEN TOKEN OK OK OK

@shop_token=605515421f8ed50a7e4f6d34f7a46bda54f3f2271e787ec279c3a964d2241b5e

@orderCode=YZL1KB2NK1GW1223

###############################################  TOKEN TOKEN TOKEN OK OK OK OK OK



################################# 查询 Active 订单 ~ OK OK OK ~ OK OK OK OK OK

POST http://192.168.0.53:3000/shop-api
Content-Type: application/json
Authorization: Bearer {{shop_token}}

{
  "query": "query { activeOrder { id code state totalWithTax lines { id productVariant { name } quantity } payments { id method state amount transactionId }  shippingLines { id priceWithTax shippingMethod { id code name description } } } }"
}


################################# 查询 Active 订单 ~ OK OK OK ~ OK OK OK OK OK



#################################  转换 Active 订单 ~ OK OK OK ~ OK OK OK OK OK
### 2️⃣ 转换 Active 订单 ArrangingPayment  / AddingItems / PaymentSettled ~ OK 

POST http://192.168.0.53:3000/shop-api
Content-Type: application/json
Authorization: Bearer {{shop_token}}

{
  "query": "mutation TransitionOrder($state: String!) { transitionOrderToState(state: $state) { ... on Order { id code state } ... on OrderStateTransitionError { message } } }",
  "variables": {
    "state": "ArrangingPayment"
  }
}

### 2️⃣ 转换 Active 订单 ArrangingPayment  / AddingItems / PaymentSettled ~ OK 
#################################  转换 Active 订单 ~ OK OK OK ~ OK OK OK OK OK




###########  Omise Prompt 第二步，在 Omise 中创建 Charge， 2025-12-12- 成功了 OK OK OK

#########  100% 100% 100%

POST http://192.168.0.53:3000/shop-api
Content-Type: application/json
Authorization: Bearer {{shop_token}}

{
    "query": "mutation CreateCharge { createOmisePromptPayCharge { qrCodeUrl } }"
}

#########  100% 100% 100%


######### 40% 40% 40% 40%

POST http://192.168.0.53:3000/shop-api
Content-Type: application/json
Authorization: Bearer {{shop_token}}

{
    "query": "mutation CreateCharge { createOmisePromptPayPartialCharge { qrCodeUrl } }"
}

######### 40% 40% 40% 40%


###########  Omise Prompt 第二步，在 Omise 中创建 Charge， 2025-12-12- 成功了 OK OK OK





###########  Omise Prompt 第三步，在 Vendure 中创建 Payment， 2025-12-13- 成功了 OK OK


### 3. Add the payment to the order, triggering the handler
### Final Step: Add the payment to the order
POST http://192.168.0.53:3000/shop-api
Content-Type: application/json
Authorization: Bearer {{shop_token}}

{
  "query": "mutation AddPayment($input: PaymentInput!) { addPaymentToOrder(input: $input) { ... on Order { id state payments { id state transactionId errorMessage } } ... on ErrorResult { errorCode message } } }",
  "variables": {
    "input": {
      "method": "omise-promptpay",
      "metadata": {
        "transactionId": "chrg_test_66115pyg81584qj79fa"
      }
    }
  }
}

###########  Omise Prompt 第三步，在 Vendure 中创建 Payment， 2025-12-13- 成功了 OK OK

####

{
  "query": "mutation AddPayment($input: PaymentInput!) { addPaymentToOrder(input: $input) { ... on Order { id state payments { id state transactionId errorMessage } } ... on ErrorResult { errorCode message } } }",
  "variables": {
    "input": {
      "method": "omise-promptpay",
      "metadata": {
        "transactionId": "chrg_test_660mnw9485f20sg0hab"
      }
    }
  }
}

#################################  Omise Prompt 第三步，未测试 














































######################### NowPayments Gemini 部分支付 Active 订单 ~ OK OK OK ~ OK OK OK OK OK

### Test a partial payment of $10.00
POST http://192.168.0.53:3000/shop-api
Content-Type: application/json
Authorization: Bearer {{shop_token}}

{
    "query": "mutation InitiateCustomPayment($amount: Int) { initiateNowPaymentsPayment(amount: $amount) }",
    "variables": {
        "amount": 10000
    }
}

######################### NowPayments Gemini 部分支付 Active 订单 ~ OK OK OK ~ OK OK OK OK OK



######################### NowPayments Gemini 全部支付 Active 订单 ~ OK OK OK ~ OK OK OK OK OK

### Test a partial payment of $10.00
POST http://192.168.0.53:3000/shop-api
Content-Type: application/json
Authorization: Bearer {{shop_token}}

{
    "query": "mutation { initiateNowPaymentsPayment }"
}

######################### NowPayments Gemini 全部支付 Active 订单 ~ OK OK OK ~ OK OK OK OK OK


