GET https://m.tu-bo.com/api/applet/colorBook/getRecipe/579118934847557 HTTP/1.1
Host: m.tu-bo.com
Connection: keep-alive
Language: zh_CN
Tubo-Sign: 0400f773c7e6f103bb9d09e43a7bda8a
Authorization: 2609a5c1a5e84117be16ad8997b2747d
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 MicroMessenger/7.0.20.1781(0x6700143B) NetType/WIFI MiniProgramEnv/Windows WindowsWechat/WMPF WindowsWechat(0x63090a13) UnifiedPCWindowsWechat(0xf2541936) XWEB/19823
xweb_xhr: 1
Content-Type: application/json
Accept: */*
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://servicewechat.com/wx245884ef5eb4d961/41/page-frame.html
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9